var fs = require('fs');

// Create the refinance page
fs.mkdirSync('src/app/refinance', { recursive: true });
fs.writeFileSync('src/app/refinance/page.tsx', [
'import RefinanceCalculator from "@/components/RefinanceCalculator";',
'',
'export default function RefinancePage() {',
'  return (',
'    <main className="min-h-screen bg-slate-50">',
'      <div className="max-w-3xl mx-auto px-4 py-12">',
'        <div className="mb-8">',
'          <h1 className="text-3xl font-bold text-slate-900 mb-2">Cash Out Refinance Calculator</h1>',
'          <p className="text-slate-500">See how much cash you can pull from your property with a refinance.</p>',
'        </div>',
'        <RefinanceCalculator />',
'      </div>',
'    </main>',
'  );',
'}',
].join('\n'));
console.log('Created refinance page');

// Create the calculator component
fs.writeFileSync('src/components/RefinanceCalculator.tsx', [
'"use client";',
'import { useState } from "react";',
'',
'export default function RefinanceCalculator() {',
'  const [form, setForm] = useState({',
'    currentValue: "",',
'    mortgageBalance: "",',
'    interestRate: "7.5",',
'    loanTerm: "30",',
'    ltv: "75",',
'    closingCosts: "3",',
'  });',
'  const [result, setResult] = useState<any>(null);',
'',
'  const calculate = () => {',
'    const value = parseFloat(form.currentValue) || 0;',
'    const balance = parseFloat(form.mortgageBalance) || 0;',
'    const rate = parseFloat(form.interestRate) / 100 / 12;',
'    const term = parseFloat(form.loanTerm) * 12;',
'    const ltv = parseFloat(form.ltv) / 100;',
'    const closingPct = parseFloat(form.closingCosts) / 100;',
'',
'    const maxLoan = value * ltv;',
'    const cashOut = maxLoan - balance;',
'    const closingCostsDollar = maxLoan * closingPct;',
'    const cashInPocket = cashOut - closingCostsDollar;',
'    const monthlyPayment = (maxLoan * rate * Math.pow(1 + rate, term)) / (Math.pow(1 + rate, term) - 1);',
'',
'    let recommendation = "PROCEED";',
'    let reason = "Good cash out with reasonable payment.";',
'    if (cashInPocket < 10000) {',
'      recommendation = "RECONSIDER";',
'      reason = "Cash out amount may not justify closing costs.";',
'    } else if (monthlyPayment > value * 0.01) {',
'      recommendation = "CAUTION";',
'      reason = "New payment is high relative to property value.";',
'    }',
'',
'    setResult({',
'      maxLoan: maxLoan.toFixed(0),',
'      cashOut: cashOut.toFixed(0),',
'      closingCostsDollar: closingCostsDollar.toFixed(0),',
'      cashInPocket: cashInPocket.toFixed(0),',
'      monthlyPayment: monthlyPayment.toFixed(0),',
'      recommendation,',
'      reason,',
'    });',
'  };',
'',
'  const update = (field: string, value: string) => setForm({ ...form, [field]: value });',
'',
'  return (',
'    <div className="space-y-6">',
'      <div className="bg-white border border-slate-200 rounded-2xl p-6 space-y-4">',
'        <div>',
'          <label className="block text-sm font-medium text-slate-700 mb-1">Current Property Value ($)</label>',
'          <input type="number" placeholder="350000" value={form.currentValue}',
'            onChange={e => update("currentValue", e.target.value)}',
'            className="w-full border border-slate-300 rounded-lg px-4 py-3 text-sm" />',
'        </div>',
'        <div>',
'          <label className="block text-sm font-medium text-slate-700 mb-1">Current Mortgage Balance ($)</label>',
'          <input type="number" placeholder="180000" value={form.mortgageBalance}',
'            onChange={e => update("mortgageBalance", e.target.value)}',
'            className="w-full border border-slate-300 rounded-lg px-4 py-3 text-sm" />',
'        </div>',
'        <div className="grid grid-cols-2 gap-4">',
'          <div>',
'            <label className="block text-sm font-medium text-slate-700 mb-1">Interest Rate (%)</label>',
'            <input type="number" step="0.1" value={form.interestRate}',
'              onChange={e => update("interestRate", e.target.value)}',
'              className="w-full border border-slate-300 rounded-lg px-4 py-3 text-sm" />',
'          </div>',
'          <div>',
'            <label className="block text-sm font-medium text-slate-700 mb-1">Loan Term (years)</label>',
'            <input type="number" value={form.loanTerm}',
'              onChange={e => update("loanTerm", e.target.value)}',
'              className="w-full border border-slate-300 rounded-lg px-4 py-3 text-sm" />',
'          </div>',
'        </div>',
'        <div className="grid grid-cols-2 gap-4">',
'          <div>',
'            <label className="block text-sm font-medium text-slate-700 mb-1">Max LTV (%)</label>',
'            <input type="number" value={form.ltv}',
'              onChange={e => update("ltv", e.target.value)}',
'              className="w-full border border-slate-300 rounded-lg px-4 py-3 text-sm" />',
'            <p className="text-xs text-slate-400 mt-1">Typical: 70-80% for cash out</p>',
'          </div>',
'          <div>',
'            <label className="block text-sm font-medium text-slate-700 mb-1">Closing Costs (%)</label>',
'            <input type="number" step="0.1" value={form.closingCosts}',
'              onChange={e => update("closingCosts", e.target.value)}',
'              className="w-full border border-slate-300 rounded-lg px-4 py-3 text-sm" />',
'          </div>',
'        </div>',
'        <button onClick={calculate}',
'          className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 rounded-xl transition-colors">',
'          Calculate Refinance',
'        </button>',
'      </div>',
'',
'      {result && (',
'        <div className="space-y-4">',
'          <div className={`border rounded-2xl p-6 ${',
'            result.recommendation === "PROCEED" ? "bg-green-50 border-green-200" :',
'            result.recommendation === "CAUTION" ? "bg-yellow-50 border-yellow-200" :',
'            "bg-red-50 border-red-200"',
'          }`}>',
'            <div className="flex items-center gap-3 mb-2">',
'              <span className={`text-white font-bold px-4 py-1 rounded-lg ${',
'                result.recommendation === "PROCEED" ? "bg-green-600" :',
'                result.recommendation === "CAUTION" ? "bg-yellow-500" :',
'                "bg-red-500"',
'              }`}>{result.recommendation}</span>',
'              <p className="text-slate-700 text-sm">{result.reason}</p>',
'            </div>',
'          </div>',
'',
'          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">',
'            <div className="bg-white border border-slate-200 rounded-xl p-4">',
'              <p className="text-xs text-slate-500 mb-1">New Loan Amount</p>',
'              <p className="text-xl font-bold text-slate-900">${Number(result.maxLoan).toLocaleString()}</p>',
'            </div>',
'            <div className="bg-white border border-slate-200 rounded-xl p-4">',
'              <p className="text-xs text-slate-500 mb-1">Cash Out</p>',
'              <p className="text-xl font-bold text-blue-600">${Number(result.cashOut).toLocaleString()}</p>',
'            </div>',
'            <div className="bg-white border border-slate-200 rounded-xl p-4">',
'              <p className="text-xs text-slate-500 mb-1">Closing Costs</p>',
'              <p className="text-xl font-bold text-red-600">${Number(result.closingCostsDollar).toLocaleString()}</p>',
'            </div>',
'            <div className="bg-white border border-slate-200 rounded-xl p-4">',
'              <p className="text-xs text-slate-500 mb-1">Cash In Pocket</p>',
'              <p className="text-xl font-bold text-green-600">${Number(result.cashInPocket).toLocaleString()}</p>',
'            </div>',
'            <div className="bg-white border border-slate-200 rounded-xl p-4 col-span-2">',
'              <p className="text-xs text-slate-500 mb-1">New Monthly Payment</p>',
'              <p className="text-xl font-bold text-slate-900">${Number(result.monthlyPayment).toLocaleString()}/mo</p>',
'            </div>',
'          </div>',
'        </div>',
'      )}',
'    </div>',
'  );',
'}',
